name: PPP approval workflow

on: pull_request_review

jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    name: PPPLabelWhenAproved
    steps:
    - name: botAproved
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "3"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "botApproved"    
